apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blueocean
  labels:
    name: blueocean
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: blueocean
    spec:
      containers:
      - name: blueocean
        image: docker.io/jenkinsci/blueocean:latest
        ports:
        - name: blueocean
          containerPort: 8080
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: blueocean
  labels:
    name: blueocean
    version: v1.5.0
  namespace: jenkins
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
  selector:
    name: blueocean
